# -*- coding: utf-8 -*-
"""23-12-28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12DZ4qbj97kh0o_9JgUD0AmGFPv9DhJ9O
"""

#2-1
print('부산대학교')
print('기초교육원')
print('컴퓨팅적 사고와 코딩')

#2-2
print("부산대학교")
print("기초교육원")
print("컴퓨팅적 사고와 코딩")

#2-3
print("""One
Two
Three""")

